# Restart webpack-watcher or webpack-dev-server if you make changes here
default: &default
  config: client
  entry: HelloWorld/startup
  output: public/assets/webpack
  manifest: manifest.json
  node_modules: client/node_modules
  source: client/app/bundles
  extensions:
    - .js
    - .jsx
    - .sass
    - .scss
    - .css

development:
  <<: *default

test:
  <<: *default
  manifest: manifest-test.json

production:
  <<: *default
